DB_TOKEN = "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"

OPENAI_API_KEY = "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"

DB_USERNAME = "lucianohcl"

DB_PATH = "rascunhos"



SHEETS_WEBHOOK = "https://script.google.com/macros/s/AKfycbzsFRYCrBtA3FqJx2lzt9BS7QoHG_g53P5AuhdxqINXcMUrmyxLWwVsZXC78XMKGF7XcQ/exec"